### ISSUE TITLE
Add !SearchTopic 

### ISSUE THREAD

**Issue by Evert-Arends** [Roobarb/hkjl-bot#15]
hackenkunjeleren.nl has a lot of tutorials, it would be nice if we could search for those in IRC. 

!Searchtopic 'Wat is hacken' => 'https://www.hackenkunjeleren.nl/introductie-wat-is-hacken-is-deze-site-voor-mij/'

**Comment by Roobarb** [comment]
duplicate of https://github.com/Roobarb/hkjl-bot/issues/6
